#index:
#    path: /
#    controller: App\Controller\DefaultController::index

cart:
  path: /cart
  controller: App\Controller\CartController::getCart

productList:
  path: /products
  controller: App\Controller\ProductListController::getProductList
